version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    network_mode: "host"  # Use the host network mode
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:

